In [3]:
import numpy as np

In [31]:
data = [[0.9526, -0.246, -0.8856],[0.5639, 0.2379, 0.9104]]

In [32]:
print(data)

[[0.9526, -0.246, -0.8856], [0.5639, 0.2379, 0.9104]]


In [33]:
arr1 = np.array(data)

In [34]:
arr1

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [35]:
print(arr1)

[[ 0.9526 -0.246  -0.8856]
 [ 0.5639  0.2379  0.9104]]


In [36]:
arr1*10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [37]:
arr1-arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [43]:
x=np.array([[0,1],[2,3]])
x

array([[0, 1],
       [2, 3]])

In [44]:
x.dtype

dtype('int64')

In [45]:
type(x.dtype)

numpy.dtype

# The Numpy ndarray: A Multidimensional Array Object

In [48]:
import numpy as np

In [49]:
a = np.arange(15).reshape(3, 5)

In [50]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
a.shape

(3, 5)

In [57]:
a.ndim

2

In [58]:
a.dtype.name

'int64'

In [59]:
a.itemsize

8

In [60]:
a.size

15

In [61]:
type(a)

numpy.ndarray

In [63]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [64]:
type(b)

numpy.ndarray

# Data Types for ndarrays

In [120]:
import numpy as np

In [121]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [122]:
arr1.dtype

dtype('float64')

In [123]:
import numpy as np

In [124]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [125]:
arr.dtype

dtype('int64')

In [126]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [127]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [128]:
numeric_strings = np.array(['1.25','-9.6','42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [135]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [137]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [140]:
a = np.array([1,2,3], float)
a.tolist()

[1.0, 2.0, 3.0]

In [155]:
list(a)

[1.0, 2.0, 3.0]

In [156]:
a = np.array([1,2,3], float)
s = a.tostring() #==np.tobytes()
s

/Users/heoinhaeng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [157]:
np.fromstring(s)

/Users/heoinhaeng/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

# Array Creation

In [172]:
np.array([1,2,3])

array([1, 2, 3])

In [173]:
np.ones(3)

array([1., 1., 1.])

In [174]:
np.zeros(3)

array([0., 0., 0.])

In [175]:
np.random.random(3)

array([0.89360111, 0.20778631, 0.26153104])

In [5]:
a = np.array([2,3,4])
a.dtype
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [6]:
b = np.array([(1.5, 2, 3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array([[1,2],[3,4]], dtype=complex)             # complex 복소수
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [24]:
np.ones_like(a)

array([1, 1, 1])

In [25]:
np.arange(10,30,5) # 10부터 30까지, 5간격으로 나타내기

array([10, 15, 20, 25])

In [28]:
np.linspace(0,2,9) # 0부터 2까지 9개로 나타내기(간격은 자동으로 정해줌)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
np.linspace(0,99,100).reshape(10,10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [38]:
mean = 0
std = 1
np.random.normal(mean, std, (2,3))
a = np.random.randn(2,3)
a

array([[ 1.61987498, -0.11870681,  0.18492175],
       [ 0.4153617 ,  0.89387598, -0.47498257]])

In [45]:
data = np.random.normal(0,1,10000)
data
import matplotlib.pyplot as plt
plt.hist(data, bins=100)

(array([  1.,   2.,   2.,   1.,   0.,   3.,   2.,   0.,   2.,   4.,   2.,
          5.,   7.,   9.,  12.,  15.,  10.,  17.,  26.,  18.,  37.,  35.,
         36.,  41.,  58.,  63.,  89.,  81.,  88.,  98., 119., 124., 153.,
        159., 178., 210., 204., 212., 228., 242., 273., 236., 261., 287.,
        309., 306., 296., 315., 306., 307., 294., 272., 304., 308., 262.,
        269., 260., 235., 216., 223., 182., 214., 161., 164., 149., 144.,
        136.,  98.,  82.,  77.,  64.,  66.,  49.,  45.,  34.,  38.,  20.,
         23.,  16.,  17.,  20.,  18.,   6.,  14.,   8.,   6.,   4.,   3.,
          3.,   3.,   0.,   1.,   1.,   0.,   1.,   0.,   0.,   0.,   0.,
          1.]),
 array([-3.7555287 , -3.67808753, -3.60064637, -3.5232052 , -3.44576403,
        -3.36832286, -3.2908817 , -3.21344053, -3.13599936, -3.05855819,
        -2.98111703, -2.90367586, -2.82623469, -2.74879352, -2.67135236,
        -2.59391119, -2.51647002, -2.43902885, -2.36158769, -2.28414652,
        -2.20670535, -2.12

In [52]:
a = np.random.rand(3, 2)
a

array([[0.93549861, 0.83182824],
       [0.99440597, 0.57708678],
       [0.6451475 , 0.97450246]])

In [53]:
data = np.random.rand(10000)
import matplotlib.pyplot as plt
plt.hist(data, bins=10)
plt.show()

In [63]:
a = np.random.randint(5, 10, size=(2,4))
a

array([[5, 6, 6, 6],
       [7, 8, 5, 8]])

In [87]:
np.random.random((2,2))

array([[0.77600531, 0.55095838],
       [0.3810734 , 0.52926578]])

In [88]:
np.random.randint(0,10,(2,3))

array([[1, 5, 4],
       [2, 8, 3]])

In [89]:
np.random.random((2,2))

array([[0.82509486, 0.83613181],
       [0.07539491, 0.01140079]])

In [90]:
np.random.randint(0,10,(2,3))

array([[6, 3, 4],
       [7, 6, 3]])

In [91]:
np.random.seed(100)

In [92]:
np.random.random((2,2))

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613]])

In [93]:
np.random.randint(0,10,(2,3))

array([[4, 2, 5],
       [2, 2, 2]])

In [94]:
np.random.random((2,2))

array([[0.13670659, 0.57509333],
       [0.89132195, 0.20920212]])

In [95]:
np.random.randint(0,10,(2,3))

array([[0, 9, 6],
       [2, 4, 1]])

# Shape Manipulation(reshaping)

In [98]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [100]:
a = a.reshape((5,2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [101]:
a.shape

(5, 2)

In [103]:
int_array1 = np.arange(10).reshape(2,5)
int_array2 = np.arange(10).reshape(-1,5)

In [104]:
int_array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
int_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
a = np.random.randint(1,10,(2,6))
a
a.resize((2,10))
print(a)
a.resize((2,2))
print(a)

[[3 4 2 1 7 6 3 1 1 2]
 [6 3 0 0 0 0 0 0 0 0]]
[[3 4]
 [2 1]]


In [126]:
a = np.array([[1,2,3],[4,5,6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [129]:
a.flatten()

array([4, 7, 2, 5, 4, 2])

In [137]:
a = np.random.randint(1,10,(2,3))
a
a.ravel()

array([4, 4, 4, 5, 8, 8])

In [161]:
a1 = np.array([[1,2],[3,4]])

a2 = a1.ravel() 
a2 = a1.reshape(-1)
a2 = a1.flatten()

a1
a2

a1[0][0]=99

# Shape Manipulation(transposing)

In [169]:
a = np.array(range(6), float).reshape((2,3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [170]:
a.transpose() == a.T
a.T

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

# Shape Manipulation(array insertion/deletion)

In [218]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [219]:
b = np.arange(6,10).reshape(2,2)
b

array([[6, 7],
       [8, 9]])

In [220]:
result1 = np.append(a,b)
result1

array([1, 2, 3, 4, 6, 7, 8, 9])

In [221]:
result2 = np.append(a,b,axis=0)
result2

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [222]:
result3 = np.append(a,b,axis=1)
result3

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [233]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
result1 = np.insert(a,1,999)
result1

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [243]:
result2 = np.insert(a, 1, 999, axis=0)
result2

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [244]:
result3 = np.insert(a,1,999, axis=1)
result3

array([[  1, 999,   2,   3],
       [  4, 999,   5,   6],
       [  7, 999,   8,   9]])

In [254]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [255]:
result1 = np.delete(a,1)
result1

array([1, 3, 4, 5, 6, 7, 8, 9])

In [257]:
result2 = np.delete(a,1,axis=0)
result2

array([[1, 2, 3],
       [7, 8, 9]])

In [259]:
result3 = np.delete(a,1,axis=1)
result3

array([[1, 3],
       [4, 6],
       [7, 9]])